language: node_js
node_js:
  - "node"
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "6.0"
  - "6.4"
  - "7"
  - "8"
  - "8.11.0"
  - "8.11.1"
  - "8.11.2"
  - "8.11.3"
  - "8.11.4"
  - "8.12.0"
  - "9"
  - "iojs"
  - "iojs-v2.4.0"
  - "iojs-v3.2.0"

notifications:
  email: ["andri@dot.ee"]
